[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -p no:cacheprovider -s -v --html=reports/report.html --self-contained-html
markers =
    smoke: vital test cases (high priority)
    regression: all functional test cases
    api: tests for the API layer



















































































